### ISSUE TITLE
[Suggest] Add a menu option to reduce comparing times

### ISSUE THREAD

**Issue by zxeoc** [greydust/mhrise-talisman_organizer#5]
Can you add a menu option like this:
When checked, the plugin considers all locked talismans as the best ones in the last organizing, and all unlocked ones as "new ones". Then it's unnecessary to compare between locked ones. That would save a lot of comparing.

**Comment by greydust** [comment]
I added this feature in 1.5.0. Thanks for the suggestion.
The option is called "skip locked talismans" and is defaulted to on. This would make the behavior more consistent.
